### ISSUE TITLE
Resource locking

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-cursor-pagination#2]
This issue was raised originally during the call for adoption.

How does the specification address locking resources when a resource is part of an active cursor?  Does this prevent updates to the underlying resources?

**Comment by dhs-aws** [comment]
Today's WG meeting discussed this issue at length.  The only item we came to a general consensus on is that locking resources when a cursor is open is undesirable and a potential security flaw.  

We did not come to any conclusions on whether cursors are point in time or strongly consistent reads.  Please add your use cases to #3 in order to help identify which of these patterns is the desired end state.

**Comment by jaudriga** [comment]
I agree with what was said during yesterday's WG meeting that defining two options might not be desirable for interoperability reasons.

As far as I can see one important use case for cusor-based pagination is paging through large amounts of data. In recent discussions one important aspect was that caching large amounts of data may lead to high resource consumption and potentially DoS. For point in time read, it is my understanding that the whole data set would need to be cached. For the other option keeping references to the result set should suffice. This is probably an important disadvantage of point in time, when the goal is paging through a really large data set.

On another note it seems that not all systems support strongly consistent read. E.g. [Amazon DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html) does not support it in all circumstances.

Instead of having two options here it might make sense to state that the result set will contain "eventually consistent" data? This would not impose additional requirements on SCIM server implementations. Of course clients would then need to cope with the situation that results will be partially up to date regarding the point in time when they opened up their cursor. As far as I can see will then affect how clients handle future delta queries.

**Comment by dhs-aws** [comment]
s/gaurantees/guarantees/ in the previous comment.

**Comment by dhs-aws** [comment]
Given the progress on the draft and WGLC, I will close this issue.
